#      _       _ _                          _
#  ___| |_ ___| | |   ___ ___ ___ _____ ___| |_
# |_ -|   | -_| | |  | . |  _| . |     | . |  _|
# |___|_|_|___|_|_|  |  _|_| |___|_|_|_|  _| |
#                    |_|               |_| |__|
# ──────────────────────────────────────────────────────────────────────────────
# Changes the default shell prompt to something a bit nicer.

[character]
success_symbol = '[\$](bold green)'
error_symbol   = '[\$](bold red)'

[directory]
read_only = " (read only)"

[git_commit]
tag_disabled = false
only_detached = false

[git_status]
disabled = false

[hostname]
ssh_symbol = "⇄ "
